//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libray_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IssueBook
    {
        public int issueid { get; set; }
        public int userid { get; set; }
        public int bookid { get; set; }
        public int issuecopy { get; set; }
        public System.DateTime issuedate { get; set; }
        public System.DateTime returndate { get; set; }
        public bool status { get; set; }
        public string description { get; set; }
        public bool reserveNoOfBook { get; set; }
    
        public virtual Tbl_Book Tbl_Book { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
