//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libray_management_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Tbl_Admin
    {
        public int adminid { get; set; }
        public string admin_name { get; set; }
        public string admin_email { get; set; }
        public string password { get; set; }
        public string admin_address { get; set; }
        public string admin_contact { get; set; }
        public string profile { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public bool isemailverified { get; set; }
        public System.Guid activationcode { get; set; }
        public int roleid { get; set; }
    
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
