//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libray_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ReturnBook
    {
        public int returnid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> bookid { get; set; }
        public Nullable<int> returnIssuecopy { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
        public Nullable<System.DateTime> currentdate { get; set; }
    
        public virtual Tbl_Book Tbl_Book { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
