//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libray_management_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_BookFine = new HashSet<Tbl_BookFine>();
            this.Tbl_IssueBook = new HashSet<Tbl_IssueBook>();
            this.Tbl_ReturnBook = new HashSet<Tbl_ReturnBook>();
        }
    
        public int userid { get; set; }
        public string uniquename { get; set; }
        public string username { get; set; }
        public string useraddress { get; set; }
        public string gender { get; set; }
        public string contact { get; set; }
        public string userprofile { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string emailid { get; set; }
        public string password { get; set; }
        public bool isemailverified { get; set; }
        public System.Guid activationcode { get; set; }
        public int roleid { get; set; }
    
        public virtual Tbl_Role Tbl_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BookFine> Tbl_BookFine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_IssueBook> Tbl_IssueBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ReturnBook> Tbl_ReturnBook { get; set; }
    }
}
